config/routes.rb
Spree::Core::Engine.routes.draw do
  Spree::Core::Engine.add_routes do
		namespace :admin do
			resources :newsletters
		end	

		resources :newsletters
  end
end

app/models/spree/newsletter.rb
module Spree
  class Newsletter < Spree::Base
    include ActiveModel::Conversion
    include ActiveModel::Validations

    EMAIL_REGEX = /\A
	  [^\s@]+ # non-at-sign characters, at least one
	  @       # at-sign
      [^\s.@] # non-at-sign and non-period character
      [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
      \.      # period
      [^\s@]* # 0 or more non-at-sign characters, accepts any number of periods
  [^\s.@] # non-at-sign and non-period character
	  \z/x

    validates :email, format: { with: EMAIL_REGEX }, presence: true, uniqueness: true

    def self.export_csv
      CSV.generate(headers: true) do |csv|
        csv << %w{codigo email}
        all.each do |newsletter_user|
          csv << [newsletter_user.id, newsletter_user.email]
        end
      end
    end
  end
end

app/controllers/spree/admin/newsletters_controller.rb
module Spree
  module Admin
    class NewslettersController < ResourceController
      def index
        respond_to do |format|
          format.html { Spree::Newsletter.all }
          format.csv { send_data Spree::Newsletter.export_csv, filename: "usuarios_boletin-#{Date.today}.csv" }
        end
      end

      def delete
        Spree::Newsletter.find(params[:id]).destroy
        redirect_to action: 'index'
      end

      def newsletter_params
        params.require(:newsletter).permit(:email)
      end
    end
  end
end

app/controllers/spree/newsletters_controller.rb
module Spree
  class NewslettersController < Spree::StoreController
    def new
      @newsletter = Spree::Newsletter.new
    end

    def create
      @newsletter = Spree::Newsletter.new(newsletter_params)
      if @newsletter.save
        respond_with(@newsletter) do |format| 
          format.json { render json: {"status":"ok","msj":"#{Spree.t(:newsletter_ok)}"} }
        end
      else
        respond_with(@newsletter) do |format| 
          format.json { render json: {"status":"fail","msj":@newsletter.errors.full_messages.join('\n')} }
        end

      end
    end

    def newsletter_params
      params.require(:newsletter).permit(:email)
    end
  end
end

app/views/spree/admin/newsletters/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:newsletters) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to 'Exportar', admin_newsletters_path(format: :csv), :id=>"btn-export", :class=>"btn-primary" %>
<% end %>

<% if @newsletters.any? %>
  <table class="table sortable" id="listing_newsletters" data-hook>
    <thead>
      <tr data-hook="option_header">
        <th><%= Spree.t(:email) %></th>
      </tr>
    </thead>
    <tbody>
      <% @newsletters.each do |newsletter| %>
        <tr class="spree_newsletter <%= cycle('odd', 'even')%>" id="<%= spree_dom_id newsletter %>" data-hook="option_row">
          <td><%= newsletter.email %></td>
          <td class="actions actions-2 text-right">
            <%= link_to_delete(newsletter, no_text: true) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: Spree.t(:newsletters)) %>,
  </div>
<% end %>

app/views/spree/admin/shared/_newsletter_sidebar_menu.html.erb
<%= tab :newsletters, label: Spree.t(:newsletters) %>

app/views/spree/shared/_newsletter.html.erb
<%= form_for Spree::Newsletter.new, :html => { :id => form_id, :onsubmit => "submitNewsletter(event, '##{form_id}');" } do |f| %>
  <div class="<%= div %>">
    <%= f.text_field :email, :class => input, :placeholder => I18n.t(:newsletter_placeholder) %> 

    <button type="submit" class="<%= button %>">
      <% if button_name == '' %>
        <%= I18n.t(:suscribe) %>
      <% else %>
        <%= button_name %> 
      <% end %>
    </button>
  </div>
<% end %>